config/routes.rb
Rails.application.routes.draw do
  resources :project_prototypes, only: :show

  resources :activities
  get 'structure_elements/new'

  get 'shippings/index'

  get 'shippings/new'

  get 'shippings/edit'

  get 'welcome/index'

  devise_for :users
  ActiveAdmin.routes(self)
  resources :dictionaries, except: [:new, :create, :delete, :destroy] do
    resources :words do
      member do
        get :subtypes
      end
    end
  end
  resources :daily_currencies
  resources :shippings
  resources :resources
  resources :projects


  root 'welcome#index'
end

app/views/resources/_form.html.haml
%h3= title
%br
= link_to t('back'), resources_path, class: 'btn btn-danger'
= form_for(@resource, url: url, as: :resource, class: "form-control") do |f|
  .form-group.row
    .col-md-4
      = f.label t('resources.name')
      = f.collection_select(:name_id, @materials_dictionary.words, :id, :body, {selected: @resource.name_id, include_blank: t('resources.choose_name')}, {"class": "btn btn-primary btn-round form-control"})
    .col-md-4
      = f.label t('resources.category')
      = select_tag 'resource[category_id]', options_for_select(@subtype_dictionary.options, @resource.category_id), prompt: t('resources.choose_category'), class: "btn btn-primary btn-round form-control"
    .col-md-4
      = f.label t('resources.unit')
      = f.collection_select(:unit_id, @units_dictionary.words, :id, :body, {selected: @resource.unit_id, include_blank: t('resources.choose_unit')}, {class: "btn btn-primary btn-round form-control"})
  .form-group.row
    .col-md-3
      = f.label t('resources.type')
      =  select_tag 'resource[type]', options_for_select(Resource.available_resources, @resource.type), {class: "form-control", disabled: @resource.persisted?}
    .col-md-3
      = f.label t('resources.price_uah')
      = f.text_field :price_uah,  class: "form-control", mask: :float
    .col-md-3
      = f.label t('resources.price_usd')
      = f.text_field :price_usd,  class: "form-control", mask: :float
    .col-md-3
      = f.label  t('resources.price_eur')
      = f.text_field :price_eur,  class: "form-control", mask: :float
  .form-actions
    = f.submit submit_button, class: "btn btn-primary btn-round"

:javascript
  $(document).ready(function(){
    $('[mask=float]').mask('0ZZZZZ.ZZ', {
       translation: {
           'Z': {
               pattern: /[0-9]/,
               optional: true
           }
       }
    });

    $("#resource_name_id").change(function(){
       Helpers.getObjectsFromLocation('/dictionaries/#{@materials_dictionary.id}/words/' + $(this).val() + '/subtypes');
    })
  })

app/views/resources/_resource.html.haml
- resource = resource.decorate
%tr  
  %td= resource.name_body
  %td= resource.category_body
  %td= resource.to_s
  %td= resource.unit_body
  %td= resource.price_uah
  %td= resource.price_usd
  %td= resource.price_eur
  %td= resource.count
  %td
    = link_to t('resources.edit'), edit_resource_path(resource), class: 'btn btn-warning'
    = link_to t('actions.delete'), resource_path(resource), class: 'btn btn-danger', method: :delete, data: {confirm: t('r_u_sure')}

app/views/resources/edit.html.haml
= render partial: 'form', locals: {title: t('resources.edit') , url: resource_path(@resource), submit_button: t('resources.update') }

app/views/resources/index.html.haml
%h3= t('resources.plural')
%table.table
  %thead
    %th= t('resources.name')
    %th= t('resources.category')
    %th= t('resources.type')
    %th= t('resources.unit')
    %th= t('resources.price_uah')
    %th= t('resources.price_usd')
    %th= t('resources.price_eur')
    %th= t('resources.count')
  %tbody
    = render @resources
= link_to t('resources.new') , new_resource_path, class: "btn btn-info"
%hr
= paginate @resources

app/views/resources/new.html.haml
= render partial: 'form', locals: {title: t('resources.new') , url: resources_path, submit_button: t('resources.create') }